project:
  type: website
  output-dir: "docs"

execute:
  freeze: false
  cache: false
  echo: false
  message: false
  output: asis

website:
  title: "Tom Baladrón"
  site-url: "https://psynguin.github.io/"
  page-footer:
    left: "Sitio web creado con [Quarto](https://quarto.org/), por Tom Baladrón. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/psynguin
      - icon: linkedin
        href: https://www.linkedin.com/in/tom-baladr%C3%B3n-733642145/
  navbar:
    title: false
    position: right
    left:
      - text: "Home"
        href: index.qmd
    right:
      - text: "About"
        href: about.qmd
      - text: "Comisiones"
        href: comision.qmd
      - text: "Books"
        href: libros.qmd
      - text: "Blog"
        href: posts/index.qmd
      - text: "My CV"
        href: cv.qmd


lang: es

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    smooth-scroll: true
    theme:
      - flatly
      - styles/custom.scss
    css: styles/styles.css