---
title: "Books"
page-layout: full
---

::::: {.column-page}

## [Libros de Psicometría y Programación]{style="color: #2c3e50; border-bottom: 2px solid #2c3e50; padding-bottom: 10px;"}

:::: {layout-ncol=2}

::: {.card .p-3 .shadow-sm .h-100 style="border-left: 5px solid #2c3e50;"}

### Inducción UA

Un libro introductorio que pretende iniciar a un analista en las labores psicométricas y de códigos de la unidad a la que pertenezco.

[Ir al libro →](https://psynguin.github.io/InduccionUA/){.btn .btn-outline-primary .btn-sm}

:::

::: {.card .p-3 .shadow-sm .h-100 style="border-left: 5px solid #2c3e50;"}

### Enciclopedia código R

Aborda el uso y aprendizajes sobre R base y diversos paquetes que utilizo en mi día a día.

[Ir al libro →](https://psynguin.github.io/enciclopediaR/){.btn .btn-outline-primary .btn-sm}

:::

::::

<br>

## [Libros de Psicología Clínica]{style="color: #2c3e50; border-bottom: 2px solid #2c3e50; padding-bottom: 10px;"}

:::: {layout-ncol=3}

::: {.card .p-3 .shadow-sm .h-100 style="border-left: 5px solid #2c3e50;"}

### Primeros Auxilios Psicológicos

Libro introductorio sobre los PAP y sus diversos modelos.

[Ir al libro →](https://youtu.be/dQw4w9WgXcQ?si=vYDgj3Lqr1SXcEzB){.btn .btn-outline-primary .btn-sm}

:::

::: {.card .p-3 .shadow-sm .h-100 style="border-left: 5px solid #2c3e50;"}

### PAP-ABCDE

Enfoque en el modelo ABCDE de la Pontificia Universidad Católica de Chile.

[Ir al libro →](https://youtu.be/dQw4w9WgXcQ?si=vYDgj3Lqr1SXcEzB){.btn .btn-outline-primary .btn-sm}

:::

::: {.card .p-3 .shadow-sm .h-100 style="border-left: 5px solid #2c3e50;"}

### Terapia de Aceptación y Compromiso

Qué es el ACT pensando en la perspectiva y necesidad de un paciente.

[Ir al libro →](https://youtu.be/dQw4w9WgXcQ?si=vYDgj3Lqr1SXcEzB){.btn .btn-outline-primary .btn-sm}

:::

::::

:::::
